//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.5485
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.5485
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebService2Soap", Namespace="http://tempuri.org/")]
public partial class WebService2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloBlanttOperationCompleted;
    
    private System.Threading.SendOrPostCallback HelloBlantt2OperationCompleted;
    
    private System.Threading.SendOrPostCallback CheckLoginOperationCompleted;
    
    /// <remarks/>
    public WebService2() {
        this.Url = "http://clockappservice.english4u.com.tw/WebService2.asmx";
    }
    
    /// <remarks/>
    public event HelloBlanttCompletedEventHandler HelloBlanttCompleted;
    
    /// <remarks/>
    public event HelloBlantt2CompletedEventHandler HelloBlantt2Completed;
    
    /// <remarks/>
    public event CheckLoginCompletedEventHandler CheckLoginCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloBlantt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloBlantt() {
        object[] results = this.Invoke("HelloBlantt", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloBlanttAsync() {
        this.HelloBlanttAsync(null);
    }
    
    /// <remarks/>
    public void HelloBlanttAsync(object userState) {
        if ((this.HelloBlanttOperationCompleted == null)) {
            this.HelloBlanttOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloBlanttOperationCompleted);
        }
        this.InvokeAsync("HelloBlantt", new object[0], this.HelloBlanttOperationCompleted, userState);
    }
    
    private void OnHelloBlanttOperationCompleted(object arg) {
        if ((this.HelloBlanttCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloBlanttCompleted(this, new HelloBlanttCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloBlantt2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloBlantt2() {
        object[] results = this.Invoke("HelloBlantt2", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloBlantt2Async() {
        this.HelloBlantt2Async(null);
    }
    
    /// <remarks/>
    public void HelloBlantt2Async(object userState) {
        if ((this.HelloBlantt2OperationCompleted == null)) {
            this.HelloBlantt2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloBlantt2OperationCompleted);
        }
        this.InvokeAsync("HelloBlantt2", new object[0], this.HelloBlantt2OperationCompleted, userState);
    }
    
    private void OnHelloBlantt2OperationCompleted(object arg) {
        if ((this.HelloBlantt2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloBlantt2Completed(this, new HelloBlantt2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CheckLogin(string UserName, string password) {
        object[] results = this.Invoke("CheckLogin", new object[] {
                    UserName,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void CheckLoginAsync(string UserName, string password) {
        this.CheckLoginAsync(UserName, password, null);
    }
    
    /// <remarks/>
    public void CheckLoginAsync(string UserName, string password, object userState) {
        if ((this.CheckLoginOperationCompleted == null)) {
            this.CheckLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoginOperationCompleted);
        }
        this.InvokeAsync("CheckLogin", new object[] {
                    UserName,
                    password}, this.CheckLoginOperationCompleted, userState);
    }
    
    private void OnCheckLoginOperationCompleted(object arg) {
        if ((this.CheckLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckLoginCompleted(this, new CheckLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void HelloBlanttCompletedEventHandler(object sender, HelloBlanttCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloBlanttCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloBlanttCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void HelloBlantt2CompletedEventHandler(object sender, HelloBlantt2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloBlantt2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloBlantt2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void CheckLoginCompletedEventHandler(object sender, CheckLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
